# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DocFormAutoUI_Conti.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 664)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.U_LoginInfo = QtWidgets.QGroupBox(Dialog)
        self.U_LoginInfo.setGeometry(QtCore.QRect(10, 10, 371, 111))
        self.U_LoginInfo.setObjectName("U_LoginInfo")
        self.G_User_PW = QtWidgets.QTextEdit(self.U_LoginInfo)
        self.G_User_PW.setGeometry(QtCore.QRect(100, 70, 251, 31))
        self.G_User_PW.setObjectName("G_User_PW")
        self.G_User_ID = QtWidgets.QTextEdit(self.U_LoginInfo)
        self.G_User_ID.setGeometry(QtCore.QRect(100, 20, 251, 31))
        self.G_User_ID.setObjectName("G_User_ID")
        self.U_ID = QtWidgets.QLineEdit(self.U_LoginInfo)
        self.U_ID.setGeometry(QtCore.QRect(20, 20, 71, 31))
        self.U_ID.setAutoFillBackground(True)
        self.U_ID.setObjectName("U_ID")
        self.U_PW = QtWidgets.QLineEdit(self.U_LoginInfo)
        self.U_PW.setGeometry(QtCore.QRect(20, 70, 71, 31))
        self.U_PW.setAccessibleDescription("")
        self.U_PW.setObjectName("U_PW")
        self.U_SetDate = QtWidgets.QGroupBox(Dialog)
        self.U_SetDate.setGeometry(QtCore.QRect(10, 137, 371, 71))
        self.U_SetDate.setObjectName("U_SetDate")
        self.U_SetYear = QtWidgets.QLineEdit(self.U_SetDate)
        self.U_SetYear.setGeometry(QtCore.QRect(130, 23, 41, 31))
        self.U_SetYear.setObjectName("U_SetYear")
        self.G_User_SetYear = QtWidgets.QComboBox(self.U_SetDate)
        self.G_User_SetYear.setGeometry(QtCore.QRect(10, 23, 111, 31))
        self.G_User_SetYear.setObjectName("G_User_SetYear")
        self.U_SetMonth = QtWidgets.QLineEdit(self.U_SetDate)
        self.U_SetMonth.setGeometry(QtCore.QRect(320, 22, 41, 31))
        self.U_SetMonth.setObjectName("U_SetMonth")
        self.G_User_SetMonth = QtWidgets.QComboBox(self.U_SetDate)
        self.G_User_SetMonth.setGeometry(QtCore.QRect(200, 22, 111, 31))
        self.G_User_SetMonth.setObjectName("G_User_SetMonth")
        self.U_SetTime = QtWidgets.QGroupBox(Dialog)
        self.U_SetTime.setGeometry(QtCore.QRect(10, 220, 371, 151))
        self.U_SetTime.setObjectName("U_SetTime")
        self.G_User_SetHour = QtWidgets.QFontComboBox(self.U_SetTime)
        self.G_User_SetHour.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.G_User_SetHour.setObjectName("G_User_SetHour")
        self.G_User_SetMinute = QtWidgets.QFontComboBox(self.U_SetTime)
        self.G_User_SetMinute.setGeometry(QtCore.QRect(200, 30, 111, 31))
        self.G_User_SetMinute.setObjectName("G_User_SetMinute")
        self.U_SetHour = QtWidgets.QLineEdit(self.U_SetTime)
        self.U_SetHour.setGeometry(QtCore.QRect(130, 30, 41, 31))
        self.U_SetHour.setObjectName("U_SetHour")
        self.U_SetMinute = QtWidgets.QLineEdit(self.U_SetTime)
        self.U_SetMinute.setGeometry(QtCore.QRect(320, 30, 41, 31))
        self.U_SetMinute.setObjectName("U_SetMinute")
        self.U_Print_OTTable = QtWidgets.QTableView(Dialog)
        self.U_Print_OTTable.setGeometry(QtCore.QRect(10, 440, 371, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U_Print_OTTable.sizePolicy().hasHeightForWidth())
        self.U_Print_OTTable.setSizePolicy(sizePolicy)
        self.U_Print_OTTable.setMinimumSize(QtCore.QSize(0, 0))
        self.U_Print_OTTable.setSizeIncrement(QtCore.QSize(0, 0))
        self.U_Print_OTTable.setBaseSize(QtCore.QSize(0, 0))
        self.U_Print_OTTable.setObjectName("U_Print_OTTable")
        self.U_Get_GWHR = QtWidgets.QFrame(Dialog)
        self.U_Get_GWHR.setGeometry(QtCore.QRect(10, 380, 371, 51))
        self.U_Get_GWHR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.U_Get_GWHR.setFrameShadow(QtWidgets.QFrame.Raised)
        self.U_Get_GWHR.setObjectName("U_Get_GWHR")
        self.U_Get_GWHR_Proc = QtWidgets.QProgressBar(self.U_Get_GWHR)
        self.U_Get_GWHR_Proc.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.U_Get_GWHR_Proc.setProperty("value", 24)
        self.U_Get_GWHR_Proc.setObjectName("U_Get_GWHR_Proc")
        self.G_Get_GWHR = QtWidgets.QPushButton(self.U_Get_GWHR)
        self.G_Get_GWHR.setGeometry(QtCore.QRect(270, 10, 93, 31))
        self.G_Get_GWHR.setObjectName("G_Get_GWHR")
        self.U_Make_DocForm = QtWidgets.QFrame(Dialog)
        self.U_Make_DocForm.setGeometry(QtCore.QRect(10, 601, 371, 51))
        self.U_Make_DocForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.U_Make_DocForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.U_Make_DocForm.setObjectName("U_Make_DocForm")
        self.G_Make_DocForm_Proc = QtWidgets.QProgressBar(self.U_Make_DocForm)
        self.G_Make_DocForm_Proc.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.G_Make_DocForm_Proc.setProperty("value", 99)
        self.G_Make_DocForm_Proc.setObjectName("G_Make_DocForm_Proc")
        self.G_Make_DocForm = QtWidgets.QPushButton(self.U_Make_DocForm)
        self.G_Make_DocForm.setGeometry(QtCore.QRect(260, 10, 93, 31))
        self.G_Make_DocForm.setObjectName("G_Make_DocForm")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.U_LoginInfo.setTitle(_translate("Dialog", "로그인 정보"))
        self.U_ID.setText(_translate("Dialog", "아이디"))
        self.U_PW.setText(_translate("Dialog", "비밀번호"))
        self.U_SetDate.setTitle(_translate("Dialog", "기간 설정하기"))
        self.U_SetYear.setText(_translate("Dialog", "년"))
        self.U_SetMonth.setText(_translate("Dialog", "월"))
        self.U_SetTime.setTitle(_translate("Dialog", "퇴근 시간 설정하기"))
        self.G_User_SetHour.setCurrentText(_translate("Dialog", "18"))
        self.G_User_SetMinute.setCurrentText(_translate("Dialog", "00"))
        self.U_SetHour.setText(_translate("Dialog", "시"))
        self.U_SetMinute.setText(_translate("Dialog", "분"))
        self.G_Get_GWHR.setText(_translate("Dialog", "가져오기"))
        self.G_Make_DocForm.setText(_translate("Dialog", "내보내기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

